### ISSUE TITLE
Generating histogram caused laptop to crash

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#322] opened 2017-08-10 12:06 UTC
### Expected behavior

Selected a variable from the SST dataset and tried to generate a histogram.

### Actual behavior

Cate GUI and every other window froze. Had to manually shut down laptop.

### Steps to reproduce the problem

1. Open Windows Task Manager, view Processes, sort by memory.

2. Open Cate GUI. Highlight data source: **esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1**
Click on “Download and/or open remote dataset”
In “Download Data Source” window:
•	Select Time Constraint and enter start time of **2006-01-01** and end time of **2007-12-31**
•	Select Region Constraint, enter:
o	Lon. from:  **-175**
o	Lon. to: **-115**
o	Lat. from: **-10**
o	Lat. to: **10**
•	Select Variables Constraint, select variables **analysed_sst** and **analysis_error** from the list 
•	Select “Download and make local data source“ and enter Unique identifier **SST_2006_2007**
•	Ensure “Open dataset from local data source“ is unselected.
•	Click on “Download”

3. When it has downloaded, highlight data source: local.SST_2006_2007
Click on “Open local dataset”
Do not select Time Constraints, region constraints or variable constraints.
Click “Open Local”

4. **Before running this step, save all work.**
In Variables panel, select **analysed_sst** then click "Create a histogram plot"

![hc 068 1](https://user-images.githubusercontent.com/29569434/29169530-5f04ebf0-7dcc-11e7-8a89-40928efdfecc.PNG)

5. View Windows Task Manager **python.exe** process.

### Specifications 

Cate 0.9.0-dev.4
 Windows 7 Professional

**Comment by forman** [comment] 2017-09-06 08:56
This issue breaks down into two new issues:
1. Cate back-end service should never ever block the OS. We must find out what's going on here: I/O, CPU, xarray, dask, websocket, etc?
2. Users should be informed about the overall amount of data to be processed and ideally how much time it will take given a selected operation and source dataset(s). This may be a challenging problem.

**Comment by JanisGailis** [comment] 2017-09-06 15:04
Maybe what I've written in the developer guide helps:
http://ect-core.readthedocs.io/en/latest/developer_guide/dg_operation_development.html#optimization

**Comment by forman** [comment] 2017-09-13 18:33
Lets put this on the agenda for Friday

**Comment by forman** [comment] 2017-09-15 09:53
See https://docs.python.org/3.6/library/resource.html

**Comment by forman** [comment] 2017-09-15 10:35
@HelenClifton we assume the problem is caused by the(Cesium) 3D globe. Could you pls try closing the World view before creating the histogram and then try again?

**Comment by HelenClifton** [comment] 2017-09-15 13:49
@forman I cannot reproduce the issue either.
I reran the "steps to reproduce" using Cate 0.9.0-dev.6 and the histogram was generated without problems - it is the same whether the World view is open or not.

**Comment by mzuehlke** [comment] 2017-09-28 16:14
As the issue can no longer be reproduced, I will close it.

**Closed by mzuehlke** 2017-09-28 16:14 UTC
Labels: blocker, cannot_reproduce, cu_mandatory

**Comment by forman** [comment] 2017-10-10 09:28
The problem persists, as matplotlib loads all data into memory. The workaround is to compute the hiostogram using xarray/dask and then to use a simple matplotlib plot.

**Comment by mzuehlke** [comment] 2017-10-10 09:49
Maybe we could use: http://dask.pydata.org/en/latest/array-api.html#dask.array.histogram
