### ISSUE TITLE
GUI-Preferences for data store files do not overwrite conf.py

### ISSUE THREAD

**Issue by MartinMonkos** [CCI-Tools/cate#350] opened 2017-09-07 12:27 UTC
### Expected behavior

One should be able to change the "data-stores"-PATH from the GUI preferences.

### Actual behavior

Preferences for 'data-stores'-PATH in Cate-GUI do not overwrite "conf.py" in the $home/.cate-directory properly. (Actually two different conf.py's exist; see screen-shot below.)
Effect: Changing 'data-stores'-PATH via GUI does not work.

### Steps to reproduce the problem

1. Click on 'File' in Cate-GUI's panel above.
2. Select 'Preferences'
3. Click on 'Data Management' in the 'Preferences'-panel
4. Enter some user-defined 'data-stores'-PATH
5. Restart Cate-GUI

### Screen-shots
Two config-files exist:
/home/mmonkos/.cate/conf.py

![cate_conf_1](https://user-images.githubusercontent.com/31618877/30023803-4d85c9ea-9171-11e7-9b5b-3d3d1d04a55d.png)

/home/mmonkos/.cate/0.9.0.dev5/conf.py

![cate_conf_2](https://user-images.githubusercontent.com/31618877/30023824-669c5ebc-9171-11e7-93ee-6be10c393625.png)

### Specifications 

Linux, 0.9.0-dev5

**Comment by forman** [comment] 2017-09-13 18:19
@MartinMonkos `$home/.cate/conf.py` should not be used at all. Correct location of file is `$home/.cate/<version>/conf.py`. Are you sure, the latter has no effect?

**Comment by MartinMonkos** [comment] 2017-09-19 11:03
I changed the path inside $home/ .cate/conf.py when I adjusted the data store path. Maybe this caused the problem. 
Checked this issue with a fresh installation of 0.9.0-dev.6 - everything seems to work fine.

**Comment by forman** [comment] 2017-09-20 18:29
Just had a similar issue and checked more carefully.
In fact, Cate Desktop *does* modify `.cate/conf.py`, it *does not* modify `.cate/<version>/conf.py`!

When reading configuration, Cate reads both files where `.cate/<version>/conf.py` overwrites  `.cate/conf.py` settings with same name.

**Comment by forman** [comment] 2017-12-11 07:28
Problem is back in 1.0.1.dev1. 

1. Change local data store path in Cate Dektop preferences. Exit.
2. Find the correct path in `<user>/.cate/1.0.1.dev1/config.py` 
3. Restart Cate Desktop. Find it using the default data store path.

**Comment by forman** [comment] 2017-12-13 10:01
Closing this - not a bug. I forgot to shut down the Cate WebAPI service while developing. So the changed `config.py` was not loaded.

Would be nice if we auto-reload `config.py` if we detect a change.

**Closed by forman** 2017-12-13 10:01 UTC
Labels: blocker, bug, conf
