### ISSUE TITLE
Error when downloading data in a Jupyter notebook

### ISSUE THREAD

**Issue by JanisGailis** [CCI-Tools/cate#256] opened 2017-06-20 12:02 UTC
### Expected behavior

Running this in a Jupyter notebook should download the data:
```python
from cate.core.ds import DATA_STORE_REGISTRY
import cate.ops as ops
from cate.util import ConsoleMonitor

monitor = ConsoleMonitor()

data_store = DATA_STORE_REGISTRY.get_data_store('esa_cci_odp')
local_store = DATA_STORE_REGISTRY.get_data_store('local')

soil_sources = data_store.query('esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1')

s_india = '72, 8, 85, 17' # 'lon_min, lat_min, lon_max, lat_max'
```
```python
# This fails
soil_sources[0].make_local(local_name='SOIL_test',
                           region=s_india,
                           time_range='2007-01-01, 2007-12-01',
                           var_names='sm, sm_uncertainty',
                           monitor=monitor)
```

### Actual behavior

Produces a stack trace:
```
Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: started
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-eb298ed39440> in <module>()
      4                            time_range='2007-01-01, 2007-12-01',
      5                            var_names='sm, sm_uncertainty',
----> 6                            monitor=monitor)

~/Development/cate-core/cate/ds/esa_cci_odp.py in make_local(self, local_name, local_id, time_range, region, var_names, monitor)
    902         local_ds = local_store.create_data_source(local_name, region, _REFERENCE_DATA_SOURCE_TYPE, self.name,
    903                                                   meta_info=local_meta_info)
--> 904         self._make_local(local_ds, time_range, region, var_names, monitor)
    905         return local_ds
    906 

~/Development/cate-core/cate/ds/esa_cci_odp.py in _make_local(self, local_ds, time_range, region, var_names, monitor)
    738                 local_netcdf = None
    739                 try:
--> 740                     remote_netcdf = NetCDF4DataStore(dataset_uri)
    741 
    742                     local_netcdf = NetCDF4DataStore(local_filepath, mode='w', persist=True)

~/miniconda3/envs/cate/lib/python3.6/site-packages/xarray/backends/netCDF4_.py in __init__(self, filename, mode, format, group, writer, clobber, diskless, persist, autoclose)
    208                                    diskless=diskless, persist=persist,
    209                                    format=format)
--> 210         self.ds = opener()
    211         self._autoclose = autoclose
    212         self._isopen = True

~/miniconda3/envs/cate/lib/python3.6/site-packages/xarray/backends/netCDF4_.py in _open_netcdf4_group(filename, mode, group, **kwargs)
    183     import netCDF4 as nc4
    184 
--> 185     ds = nc4.Dataset(filename, mode=mode, **kwargs)
    186 
    187     with close_on_error(ds):

netCDF4/_netCDF4.pyx in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:13852)()

netCDF4/_netCDF4.pyx in netCDF4._netCDF4._ensure_nc_success (netCDF4/_netCDF4.c:12638)()

OSError: NetCDF: Invalid argument
```

### Steps to reproduce the problem

Run the above mentioned in a Jupyter notebook.

### Specifications 

Ubuntu 16.04, Cate version: '0.8.0rc5'

Note that downloading a few days of the same dataset works. Also, downloading the whole year works through the CLI.

**Comment by kbernat** [comment] 2017-06-20 14:06
@JanisGailis 
Unfortunately I cannot reproduce an issue - it works for me.
Could you provide more details about your env ?
check your python version, path to jupyter,

```python
import sys
print(sys.version, sys.path)
```

    3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) 
    [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] ['', '/home/dev/Projects/CCI-Tools/cate-core', '/opt/miniconda3/envs/cate/lib/python36.zip', '/opt/miniconda3/envs/cate/lib/python3.6', '/opt/miniconda3/envs/cate/lib/python3.6/lib-dynload', '/opt/miniconda3/envs/cate/lib/python3.6/site-packages', '/opt/miniconda3/envs/cate/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg', '/opt/miniconda3/envs/cate/lib/python3.6/site-packages/Cython-0.25.2-py3.6-linux-x86_64.egg', '/opt/miniconda3/envs/cate/lib/python3.6/site-packages/cate-0.8.0rc5-py3.6.egg', '/opt/miniconda3/envs/cate/lib/python3.6/site-packages/IPython/extensions', '/home/dev/.ipython']



```python
from cate.core.ds import DATA_STORE_REGISTRY
import cate.ops as ops
from cate.util import ConsoleMonitor

monitor = ConsoleMonitor()

data_store = DATA_STORE_REGISTRY.get_data_store('esa_cci_odp')
local_store = DATA_STORE_REGISTRY.get_data_store('local')

soil_sources = data_store.query('esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1')

s_india = '72, 8, 85, 17' # 'lon_min, lat_min, lon_max, lat_max'
```


```python
soil_sources[0].make_local(local_name='SOIL_test',
                           region=s_india,
                           time_range='2007-01-01, 2007-12-01',
                           var_names='sm, sm_uncertainty',
                           monitor=monitor)
```

    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: started
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: sm
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: sm_uncertainty
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: lon
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: lat
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc: time
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20070101000000-fv02.2.nc
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1:   0% 



    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc: sm
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc: sm_uncertainty
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc: lon
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc: lat
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc: time
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: 100% ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc
    Sync esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.02-2.r1: ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-20071201000000-fv02.2.nc

<table style="border:0;">
<tr><td>Name</td><td><strong>local.SOIL_test</strong></td></tr>
</table>

**Comment by JanisGailis** [comment] 2017-06-20 14:11
Env information:
```
3.6.1 | packaged by conda-forge | (default, May 23 2017, 14:16:20) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] ['', '/home/ccitbx/miniconda3/envs/cate/lib/python36.zip', '/home/ccitbx/miniconda3/envs/cate/lib/python3.6', '/home/ccitbx/miniconda3/envs/cate/lib/python3.6/lib-dynload', '/home/ccitbx/miniconda3/envs/cate/lib/python3.6/site-packages', '/home/ccitbx/miniconda3/envs/cate/lib/python3.6/site-packages/cycler-0.10.0-py3.6.egg', '/home/ccitbx/Development/cate-core', '/home/ccitbx/miniconda3/envs/cate/lib/python3.6/site-packages/IPython/extensions', '/home/ccitbx/.ipython']
```

**Comment by kbernat** [comment] 2017-06-20 14:12
Could you please additionally check netCDF version?
```
import netCDF4 as nc4
nc4.__version__
```
```
'1.2.9'
```

**Comment by JanisGailis** [comment] 2017-06-21 11:48
1.2.8
0.9.6

**Comment by JanisGailis** [comment] 2017-06-21 11:48
I'll try updating nc4

**Comment by JanisGailis** [comment] 2017-06-21 11:56
Now it's:
1.2.9
0.9.6

And I still have the same stack trace as above.

I suggest we leave this for now. Marco has fixed the CLI Issue that I encountered, so I can use that for happy path scripts. It is of course somewhat annoying, but I don't think it makes sense to spend much time on this. At least not now, when there are more urgent things to do.

**Comment by JanisGailis** [comment] 2017-06-22 08:07
Actually it's Ubuntu 15.10, which doesn't receive updates anymore, so maybe one of the underlying libraries is an old one that has a bug. I'll try updating to 16.04 LTS at some point and see if the problem persists.

**Comment by JanisGailis** [comment] 2017-06-29 14:58
I updated Ubuntu to 16.05, updated conda, updated my environment, pruned jupyter from it, installed jupyter anew, the problem still persists. I don't know, must be a configuration issue.

Let's not worry about this for now.

**Comment by kbernat** [comment] 2017-10-03 18:03
@JanisGailis - I still cannot reproduce it. Have you had a chance to test it on any fresh environment?

**Comment by kbernat** [comment] 2017-10-05 16:00
@forman @JanisGailis I'm going to closed it, cannot reproduce it. Perhaps it was one of many conda's environment/dependencies issues.

**Closed** 2017-10-05 16:01 UTC
Labels: bug, cannot_reproduce, ds, uc06

**Comment by forman** [comment] 2017-10-05 16:19
Ok, @JanisGailis can reopen it if the issue persists.
