### ISSUE TITLE
Closing Cate on Mac

### ISSUE THREAD

**Issue by kjpearson** [CCI-Tools/cate#551] opened 2018-03-08 13:12 UTC
### Expected behaviour

Choosing "Quit Cate" from the menu or pressing the red "close window" icon on the window should close the application.

### Actual behaviour

In both situations, the "Are you sure" prompt appears and the "Quit" option is selected. However, Cate carries on running. The only way to close Cate is to hit the red button in the corner of the window again. The "Quit Cate" action on the menu appears to have no further effect.

### Specifications 

Cate 2.0.0-dev1 iMac

**Comment by forman** [comment] 2018-03-08 15:08
Thanks for testing!
This works fine on Windows 10, seems like a platform-specific issue (in Electron).

**Comment by HelenClifton** [comment] 2018-03-09 13:04
@forman  Have seen exactly the same with cate-2.0.0-dev.1.
Tested on MacBook Pro running OS X 10.9.5

**Comment by forman** [comment] 2018-03-15 09:36
I cannot reproduce this in Cate Desktop 2.0.0-dev.3. However, I don't get any "Are you sure" prompt whether I use the red close button or "Quit" from the main menu or right clicking the dock icon.

**Comment by kjpearson** [comment] 2018-03-15 10:10
I have the same behaviour as originally described with 2.00-dev.3 except for the very first time I started it after the update. In that case the GUI closed down properly.

**Comment by forman** [comment] 2018-03-21 13:01
@kjpearson could you please check and maybe reopen if the problem persists?

**Comment by forman** [comment] 2018-03-21 14:17
Just recognized that in dev7 Cate does *not* quit on Mac if I just close its main window.

**Comment by esacci** [comment] 2018-03-23 13:25
Something similar occurs with my dev7 (Mac). How to recreate - (1) Select a big data set to get from CCI ODP source, (2) whilst the dataset is downloading, quit Cate ; it takes a few seconds to quit, do not Force Quit. (3) after Cate has closed, start Cate, (4) you will notice that on the splash screen (the message is something like starting services, something like that, underneath the project logo) this just hangs. Quitting Cate (again) does not resolve the issue. Re-booting the Mac resolves the issue. I have not tried logging out and back again (instead of rebooting Mac) to see if this resolves the issue.

**Comment by forman** [comment] 2018-03-26 16:16
This is really strange. Cate Desktop's current on-quit strategy is to ask the Cate backend service to gracefully shut down (= making a request to `http://localhost:<port>/exit`). On request timeout, after a few secs, Cate Desktop should *kill* (= sending `SIGKILL` / `kill -9`) the running Cate backend task.

**Comment by forman** [comment] 2018-04-17 12:10
Fixed in 2.0.0.dev9

**Closed by forman** 2018-04-17 12:10 UTC
Labels: bug, gui, in_progress
