### ISSUE TITLE
Failed coregistration of ocean colour with aerosol data

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#814] opened 2018-11-27 15:15 UTC
### Expected behavior

*coregister ocean colour data with aerosol data*

### Actual behavior

*coregistration of ocean colour and aerosol data failed with the error crs data array of replica dataset is not valid for coregistration. The data array is expected to have lat and lon dimensions. The data array has the following dimensions: ('time',). Consider running select_var operation to exclude this data array because:*

`Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\wsmanag.py", line 320, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ops\coregistration.py", line 111, in coregister
    ' data array'.format(key, ds_replica[key].dims))
cate.core.types.ValidationError: crs data array of replica dataset is not valid for coregistration. The data array is expected to have lat and lon dimensions. The data array has the following dimensions: ('time',). Consider running select_var operation to exclude this data array`

### Steps to reproduce the problem

1. *ocean_colour = cate.ops.open_dataset(ds_id="esacci.OC.5-days.L3S.K_490.multi-sensor.multi-platform.MERGED.2-0.r1", time_range="1998-01-01,1998-03-31", region="-20,-20,20,20", force_local=True)* 
2. *aerosol = cate.ops.open_dataset(ds_id="esacci.AEROSOL.mon.L3C.AOD.MERIS.Envisat.MERIS_ENVISAT.2-2.r1", time_range="2008-01-01,2008-03-31", region="-20,-20,20,20", force_local=True)* 
3. *perform coregitration* 

### Specifications 

*cate 2.0.0-dev-23*
*Windows 10*

**Comment by JanisGailis** [comment] 2018-11-28 09:39
This is not a bug. The error message describes what must be done to coregister the dataset:
```
Consider running select_var operation to exclude this data array
```
That it should not force users to do this is a different matter, which is an enhancement currently put in 3.0 board. See #785 

Closing this.

**Closed by JanisGailis** 2018-11-28 09:39 UTC
Labels: ops
