### ISSUE TITLE
"Write to read-only" errors when downloading datasets

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#667] opened 2018-06-07 13:10 UTC
### Expected behavior

Attempted to download different datasets: soil moisture, SST, cloud

### Actual behavior

In each case, the download starts but shortly afterwards there is an error of the following type :

![capture](https://user-images.githubusercontent.com/29569434/41100427-db7a94ca-6a50-11e8-9b1c-c35283a88df4.PNG)

Log file for soil moisture example here: 
[sm download trace.txt](https://github.com/CCI-Tools/cate/files/2080462/sm.download.trace.txt)

### Steps to reproduce the problem

1. Select esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.03-2.r1
2. Select Download Dataset to Local option with:
Time Constraint: 2007-01-01 to 2007-12-31
Region Constraint: 
o	Lon. from: 72
o	Lon. to: 85
o	Lat. from: 8
o	Lat. to: 17
Variables Constraint: sm, sm_uncertainty 

Same type of error happens with the following datasets:

esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1
Time Constraint: 2006-01-01 to 2007-12-31
Region Constraint: 
o	Lon. from: -175
o	Lon. to: -115
o	Lat. from: -10
o	Lat. to: 10
Variables Constraint: analysed_sst, analysis_error 

and

esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1
Time Constraint: 2006-01-01 to 2009-12-31
Region Constraint: 
o	Lon. from: 7
o	Lon. to: 10
o	Lat. from: 48
o	Lat. to: 52
Variables Constraint: cfc

### Note
@forman , @JanisGailis , @papesci
This problem is blocking happy path for use case 6 and use case 2
Whereas with the datasets in the use case 22 happy path, it happens at some times but not others.
It could be related to update which was made to fix #631

### Specifications 

cate-2.0.0-dev.11
Windows 7 Professional

**Comment by JanisGailis** [comment] 2018-06-07 13:11
Likely a duplicate of #664

**Comment by HelenClifton** [comment] 2018-06-11 10:19
@forman , @JanisGailis , @papesci  Same happens with dataset below. This is blocking happy path for new use case 4.

esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1
 Time Constraint: 1997-01-01 to 2008-12-31
 Region Constraint:
 o Lon. from: -160
 o Lon. to: -69
 o Lat. from: 23
 o Lat. to: 50
 Variables Constraint: O3_du_tot

**Comment by papesci** [comment] 2018-06-13 15:40
Hi I have just tried to execute all the tests mentioned in this issue on Linux with version dev13 successfully.

**Comment by HelenClifton** [comment] 2018-06-14 08:08
Hi @papesci, @forman I've repeated the tests on my Windows machine, which now has dev.13 installed, and the same problems are happening.
However, I saw that my CLI environment is still reported as dev.11:
![capture](https://user-images.githubusercontent.com/29569434/41399496-0971a306-6faa-11e8-896b-a6633cb112b3.PNG)

**Comment by papesci** [comment] 2018-06-14 13:32
@HelenClifton  cate core should be dev12. Can you open a shell and type cate --version just to confirm which core is in use ?

**Comment by HelenClifton** [comment] 2018-06-14 13:51
@papesci In the CLI, it says 2.0.0.dev.12

**Comment by HelenClifton** [comment] 2018-06-14 14:47
@papesci I tried downloading the above datasets using a mac with dev.13 installed and there were no problems. It just seems to be Windows.

**Comment by hans-permana** [comment] 2018-06-14 15:18
I can reproduce this issue on my Windows 10 Home machine. This did not happen when the variable and spatial filter were not set.

**Comment by HelenClifton** [comment] 2018-06-19 09:17
@papesci Confirmed it still has same behaviour with dev.15 using Windows

**Comment by papesci** [comment] 2018-07-10 13:44
A different behavior is confirmed when using different OS. 
After several tests, on all the supported OS included Window, the operation open_dataset of XArray react differently when a large number of files is open. The error don't appear when adding the optional parameter autoclose=True to xarray open_dataset function. I think this is more a workaround then a fix which should be implemented inside xarray library i guess.  

However a branch has been created [667](https://github.com/CCI-Tools/cate/tree/667-pp-write-to-readonly)

**Comment by JanisGailis** [comment] 2018-07-10 13:50
The ``autoclose`` option was implemented in ``xarray`` after us and other people reporting memory issues when opening datasets consisting of many files. So, that already is the fix. In either case we should use ``autoclose``, it was pretty much made for our use case.

**Closed** 2018-07-12 15:18 UTC
Labels: bug, ds
