### ISSUE TITLE
errors in correlation calculation running UC6 scenario CLI scripts

### ISSUE THREAD

**Issue by VPriemer** [CCI-Tools/cate#500] opened 2018-01-09 13:23 UTC
### Comment 
Relates to #339
 
### Expected behavior
Ran the following script in CLI:
https://github.com/CCI-Tools/cate-e2e/blob/master/scripts/UC6/UC06_S1_v002.sh
Expected no error.

### Actual behavior
cate res: error: set_workspace_resource() call raised exception: "coordinate variable "lon" is not equi-distant"
and as a consequnece it runs into a NA-correlation.

### Steps to reproduce the problem
1. Download the script 
2. Open CLI interface
3. bash UC06_S1_v002.sh

### Additional (scenario 2)
When running UC06_S2_v001.sh there is no correlation calculated:
cate res: error: print_workspace_resource() call raised exception: "The length of the time dimension differs between the given datasets. Can not perform the calculation, please review operation documentation."

Scenario 3 completes without error and the correlation is calculated.

### Specifications 
CLI, Linux, cate-1.0.0

**Comment by JanisGailis** [comment] 2018-04-03 10:57
The first issue seems to be caused by a rounding error present in the data. See the longitude dimension:
```
[-179.75       -179.25       -178.75       -178.25       -177.75
 -177.25       -176.75       -176.25       -175.75       -175.25
 -174.75       -174.25       -173.75       -173.25       -172.75
 -172.25       -171.75       -171.25       -170.75       -170.25
 -169.75       -169.25       -168.75       -168.25       -167.75
 -167.25       -166.75       -166.25       -165.75       -165.25
 -164.75       -164.25       -163.75       -163.25       -162.75
 -162.25       -161.75       -161.25       -160.75       -160.25
 -159.75       -159.25       -158.75       -158.25       -157.75
 -157.25       -156.75       -156.25       -155.75       -155.25
 -154.75       -154.25       -153.75       -153.25       -152.75
 -152.25       -151.75       -151.25       -150.75       -150.25
 -149.75       -149.25       -148.75       -148.25       -147.75
 -147.25       -146.75       -146.25       -145.75       -145.25
 -144.75       -144.25       -143.75       -143.25       -142.75
 -142.25       -141.75       -141.25       -140.75       -140.25
 -139.75       -139.25       -138.75       -138.25       -137.75
 -137.25       -136.75       -136.25       -135.75       -135.25
 -134.75       -134.25       -133.75       -133.25       -132.75
 -132.25       -131.75       -131.25       -130.75       -130.25
 -129.75       -129.25       -128.75       -128.25       -127.75
 -127.25       -126.75       -126.25       -125.75       -125.25
 -124.75       -124.25       -123.75       -123.25       -122.75
 -122.25       -121.75       -121.25       -120.75       -120.25
 -119.75       -119.25       -118.75       -118.25       -117.75
 -117.25       -116.75001    -116.25001    -115.75001    -115.25001
 -114.75001    -114.25001    -113.75001    -113.25001    -112.75001
 -112.25001    -111.75001    -111.25001    -110.75001    -110.25001
 -109.75001    -109.25001    -108.75001    -108.25001    -107.75001
 -107.25001    -106.75001    -106.25001    -105.75001    -105.25001
 -104.75001    -104.25001    -103.75001    -103.25001    -102.75001
 -102.25001    -101.75001    -101.25001    -100.75001    -100.25001
  -99.75001     -99.25001     -98.75001     -98.25001     -97.75001
  -97.25001     -96.75001     -96.25001     -95.75001     -95.25001
  -94.75001     -94.25001     -93.75001     -93.25001     -92.75001
  -92.25001     -91.75001     -91.25001     -90.75001     -90.25001
  -89.75001     -89.25001     -88.75001     -88.25001     -87.75001
  -87.25001     -86.75001     -86.25001     -85.75001     -85.25001
  -84.75001     -84.25001     -83.75001     -83.25001     -82.75001
  -82.25001     -81.75001     -81.25001     -80.75001     -80.25001
  -79.75001     -79.25001     -78.75001     -78.25001     -77.75001
  -77.25001     -76.75001     -76.25001     -75.75001     -75.25001
  -74.75001     -74.25001     -73.75001     -73.25001     -72.75001
  -72.25001     -71.75001     -71.25001     -70.75001     -70.25001
  -69.75001     -69.25001     -68.75001     -68.25001     -67.75001
  -67.25001     -66.75001     -66.25001     -65.75001     -65.25001
  -64.75001     -64.25001     -63.750008    -63.250008    -62.750008
  -62.250008    -61.750008    -61.250008    -60.750008    -60.250008
  -59.750008    -59.250008    -58.750008    -58.250008    -57.750008
  -57.250008    -56.750008    -56.250008    -55.750008    -55.250008
  -54.750008    -54.250008    -53.750008    -53.250008    -52.750008
  -52.250008    -51.750008    -51.250008    -50.750008    -50.250008
  -49.750008    -49.250008    -48.750008    -48.250008    -47.750008
  -47.250008    -46.750008    -46.250008    -45.750008    -45.250008
  -44.750008    -44.250008    -43.750008    -43.250008    -42.750008
  -42.250008    -41.750008    -41.250008    -40.750008    -40.250008
  -39.750008    -39.250008    -38.750008    -38.250008    -37.750008
  -37.250008    -36.750008    -36.250008    -35.750008    -35.250008
  -34.750008    -34.250008    -33.750008    -33.250008    -32.750008
  -32.250008    -31.75001     -31.25001     -30.75001     -30.25001
  -29.75001     -29.25001     -28.75001     -28.25001     -27.75001
  -27.25001     -26.75001     -26.25001     -25.75001     -25.25001
  -24.75001     -24.25001     -23.75001     -23.25001     -22.75001
  -22.25001     -21.75001     -21.25001     -20.75001     -20.25001
  -19.75001     -19.25001     -18.75001     -18.25001     -17.75001
  -17.25001     -16.75001     -16.25001     -15.75001     -15.2500105
  -14.7500105   -14.2500105   -13.7500105   -13.2500105   -12.7500105
  -12.2500105   -11.7500105   -11.2500105   -10.7500105   -10.2500105
   -9.7500105    -9.2500105    -8.7500105    -8.2500105    -7.7500105
   -7.2500105    -6.7500105    -6.2500105    -5.7500105    -5.2500105
   -4.7500105    -4.2500105    -3.7500107    -3.2500107    -2.7500107
   -2.2500107    -1.7500108    -1.2500108    -0.7500109    -0.25001097
    0.24998902    0.749989      1.2499889     1.7499889     2.2499888
    2.7499888     3.2499888     3.7499888     4.2499886     4.7499886
    5.2499886     5.7499886     6.2499886     6.7499886     7.2499886
    7.7499886     8.249989      8.749989      9.249989      9.749989
   10.249989     10.749989     11.249989     11.749989     12.249989
   12.749989     13.249989     13.749989     14.249989     14.749989
   15.249989     15.749988     16.249989     16.749989     17.249989
   17.749989     18.249989     18.749989     19.249989     19.749989
   20.249989     20.749989     21.249989     21.749989     22.249989
   22.749989     23.249989     23.749987     24.249987     24.749987
   25.249987     25.749987     26.249987     26.749987     27.249987
   27.749987     28.249987     28.749987     29.249987     29.749987
   30.249987     30.749987     31.249987     31.749987     32.24999
   32.74999      33.24999      33.74999      34.24999      34.74999
   35.24999      35.74999      36.24999      36.74999      37.24999
   37.74999      38.24999      38.74999      39.249985     39.749985
   40.249985     40.749985     41.249985     41.749985     42.249985
   42.749985     43.249985     43.749985     44.249985     44.749985
   45.249985     45.749985     46.249985     46.749985     47.249985
   47.749985     48.249985     48.749985     49.249985     49.749985
   50.249985     50.749985     51.249985     51.749985     52.249985
   52.749985     53.249985     53.749985     54.249985     54.749985
   55.249985     55.749985     56.249985     56.749985     57.249985
   57.749985     58.249985     58.749985     59.249985     59.749985
   60.249985     60.749985     61.249985     61.749985     62.249985
   62.749985     63.249985     63.749985     64.249985     64.749985
   65.249985     65.749985     66.249985     66.749985     67.249985
   67.749985     68.249985     68.749985     69.249985     69.749985
   70.249985     70.749985     71.249985     71.749985     72.249985
   72.749985     73.249985     73.749985     74.249985     74.749985
   75.249985     75.749985     76.249985     76.749985     77.249985
   77.749985     78.249985     78.749985     79.249985     79.749985
   80.249985     80.749985     81.249985     81.749985     82.249985
   82.749985     83.249985     83.749985     84.249985     84.749985
   85.249985     85.749985     86.249985     86.749985     87.249985
   87.749985     88.249985     88.749985     89.249985     89.749985
   90.249985     90.749985     91.249985     91.749985     92.249985
   92.749985     93.249985     93.749985     94.249985     94.749985
   95.249985     95.749985     96.249985     96.749985     97.249985
   97.749985     98.249985     98.749985     99.249985     99.749985
  100.249985    100.749985    101.249985    101.749985    102.249985
  102.749985    103.249985    103.749985    104.249985    104.749985
  105.249985    105.749985    106.249985    106.749985    107.249985
  107.749985    108.249985    108.749985    109.249985    109.749985
  110.249985    110.749985    111.249985    111.749985    112.249985
  112.749985    113.249985    113.749985    114.249985    114.749985
  115.249985    115.749985    116.249985    116.749985    117.249985
  117.749985    118.249985    118.749985    119.249985    119.749985
  120.249985    120.749985    121.249985    121.749985    122.249985
  122.749985    123.249985    123.749985    124.249985    124.749985
  125.249985    125.749985    126.249985    126.749985    127.249985
  127.749985    128.24998     128.74998     129.24998     129.74998
  130.24998     130.74998     131.24998     131.74998     132.24998
  132.74998     133.24998     133.74998     134.24998     134.74998
  135.24998     135.74998     136.24998     136.74998     137.24998
  137.74998     138.24998     138.74998     139.24998     139.74998
  140.24998     140.74998     141.24998     141.74998     142.24998
  142.74998     143.24998     143.74998     144.24998     144.74998
  145.24998     145.74998     146.24998     146.74998     147.24998
  147.74998     148.24998     148.74998     149.24998     149.74998
  150.24998     150.74998     151.24998     151.74998     152.24998
  152.74998     153.24998     153.74998     154.24998     154.74998
  155.24998     155.74998     156.24998     156.74998     157.24998
  157.74998     158.24998     158.74998     159.24998     159.74998
  160.24998     160.74998     161.24998     161.74998     162.24998
  162.74998     163.24998     163.74998     164.24998     164.74998
  165.24998     165.74998     166.24998     166.74998     167.24998
  167.74998     168.24998     168.74998     169.24998     169.74998
  170.24998     170.74998     171.24998     171.74998     172.24998
  172.74998     173.24998     173.74998     174.24998     174.74998
  175.24998     175.74998     176.24998     176.74998     177.24998
  177.74998     178.24998     178.74998     179.24998     179.74998   ]
```

**Comment by JanisGailis** [comment] 2018-04-18 12:38
@forman I don't think this is a bug in our software, rather, the data is faulty. We can of course decide to implement some workaround here. Note that this is for one of the additional scenarios.

@VPriemer Can you try doing the additional scenarios using data from the working scenario?

**Comment by VPriemer** [comment] 2018-04-23 08:49
I've tried the additional scenario with the 'esacci.SOILMOISTURE.day.L3S.SSMV.multi-sensor.multi-platform.COMBINED.03-2.r1' data from the working happypath of UC06 (instead of the 'esacci.CLOUD.mon.L3C.CLD_PRODUCTS.MODIS.Terra.MODIS_TERRA.2-0.r1' data).

It works fine and the correlation is calculated.

**Comment by JanisGailis** [comment] 2018-06-20 08:29
Closing this as this is an issue with input data.

**Closed by JanisGailis** 2018-06-20 08:29 UTC
Labels: bug, ops, support_request, uc06
