### ISSUE TITLE
Unable to desplay fire data

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#599] opened 2018-04-01 11:13 UTC
Cate Desktop, version 2.0.0-dev.8

get_data_sources() call returned a value that could not be converted to JSON

An error (code 30) occurred in Cate Core:

null

**Comment by forman** [comment] 2018-04-22 15:57
Please tell use which dataset exactly you are referring to.

**Comment by Evadzi** [comment] 2018-04-23 07:29
@forman 
Everything works fine now. I cant tell why it works now and not before..

**Comment by forman** [comment] 2018-04-30 12:29
Closing this as we cannot reproduce it again.

**Closed by forman** 2018-04-30 12:29 UTC
Labels: bug, cannot_reproduce, ds, webapi
