### ISSUE TITLE
Local dataset not recognised

### ISSUE THREAD

**Issue by kjpearson** [CCI-Tools/cate#557] opened 2018-03-13 12:05 UTC
I'm running the CLI steps given by @JanisGailis in #538 but the dataset I have just downloaded is not recognised.

**(cate)** $ cate ds list
....
 170: local.SST CCI subset 2000-2001
 171: local.SST CCI subset sep 1991-aug 1993
 172: local.SST_2006_2007
 173: local.esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1.dca2f503-7ee0-32ef-a200-afdf8ae650b
**(cate)** $ cate ws init
Workspace initialized.
**(cate)** $ cate res open sst local.SST_2006_2007
Traceback (most recent call last):
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/util/web/jsonrpchandler.py", line 192, in send_service_method_result
    result = future.result()
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/util/web/jsonrpchandler.py", line 271, in call_service_method
    result = method(**method_params, monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/webapi/websocket.py", line 284, in set_workspace_resource
    monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/wsmanag.py", line 323, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workspace.py", line 599, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/op.py", line 215, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/ops/io.py", line 81, in open_dataset
    monitor=monitor)
  File "/Users/kevinpearson/cate-2.0.0.dev1/lib/python3.6/site-packages/cate/core/ds.py", line 503, in open_dataset
    raise ValueError("No data_source found for the given query term", data_source)
ValueError: ('No data_source found for the given query term', 'local.SST_2006_2007')

cate res: error: set_workspace_resource() call raised exception: "('No data_source found for the given query term', 'local.SST_2006_2007')"

**Comment by forman** [comment] 2018-03-14 12:02
There may be a problem in `cate.core.ds` or `cate.ds.local`, but there is also a problem in the CLI, as such stack traces should only be printed when given the option `--traceback`.

**Comment by forman** [comment] 2018-03-14 12:10
Just started Cate Desktop dev3 which loaded my previous workspace and I got:

![image](https://user-images.githubusercontent.com/206773/37401627-fda46608-2788-11e8-98c4-62504929b302.png)

Traceback:

      File "D:\Projects\cate\cate\core\workflow.py", line 318, in invoke
        self._invoke_impl(_new_context(context, step=self), monitor=monitor)
      File "D:\Projects\cate\cate\core\workflow.py", line 980, in _invoke_impl
        return_value = self._op(monitor=monitor, **input_values)
      File "D:\Projects\cate\cate\core\op.py", line 215, in __call__
        return_value = self._wrapped_op(**input_values)
      File "D:\Projects\cate\cate\ops\io.py", line 81, in open_dataset
        monitor=monitor)
      File "D:\Projects\cate\cate\core\ds.py", line 505, in open_dataset
        raise ValueError("%s data_sources found for the given query term '%s'" % (len(data_sources), data_source))
    ValueError: 2 data_sources found for the given query term 'local.2010.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1'

**Comment by forman** [comment] 2018-03-15 08:46
Very strange, I could not reproduce my bug today.

**Comment by papesci** [comment] 2018-03-27 13:19
The local data Store should be updated every time the user ask to open a resource. At the present moment the update is done only at the time of web server lunch. So when the user create a new local DS and the webapi process is already running the data set is not properly inserted in the list.

**Comment by papesci** [comment] 2018-04-03 11:12
I made a new branch 
[557 local-ds-not-visible](https://github.com/CCI-Tools/cate/tree/557-pp-local-ds-not-visible)
which fix the current issue

**Comment by forman** [comment] 2018-05-01 13:00
@papesci please see my review so we merge and can close this.

**Comment by forman** [comment] 2018-05-07 08:46
@HelenClifton considers this being fixed now. Closing it.

**Closed by forman** 2018-05-07 08:46 UTC
Labels: blocker, bug, cli, ds
