### ISSUE TITLE
Operations hanging and can't cancel

### ISSUE THREAD

**Issue by kjpearson** [CCI-Tools/cate#549] opened 2018-03-08 12:56 UTC
This may be difficult to reproduce but it's serious enough to warrant an issue as I've had a number of occasions where the operation seems to be running but must have become stuck somehow.

I have had a several situations where the GUI indicated that an operation is running but after a while it becomes clear that it's taken much longer than usual to complete. On those occasions I've tried to hit the cancel button but it has no effect. The data display on the globe still rotates and zooms and I can initiate new operations but  the processing doesn't finish. The only solution is to restart Cate.

A similar thing seems to happen if I open a local data source on a remote mounted disk and then the link to the disk goes down. Cate still displays activity for the loading of the dataset but even if the connection the remote disk is established the process doesn't complete. There is no "cancel" button for the open local data source operation.

### Specifications 

Cate v2.0.0 dev1 iMac

**Comment by forman** [comment] 2018-03-08 14:51
Happened to me some moments ago, but I cannot reproduce it in a new session.
In the previous session I opened a CCI dataset subset remotely from ODP (cloud coverage). 
In the new session I only used local data.
Just a suspicion.

**Comment by forman** [comment] 2018-04-17 11:12
May be related to and fixed by #606

**Comment by forman** [comment] 2018-05-14 10:33
@kjpearson do you still encounter this behaviour in dev10?

**Comment by kjpearson** [comment] 2018-05-21 09:50
So far I've not had the processing hang on me in dev10. However, there are some operations that don't have a cancel button and that can take some time like "open_dataset" and, I think, "write_netcdf4". The last command took a surprising 5 hours to write out a 2.5 GB file (a single 12x3600x7200 array) although I may have been short on memory at this point in the processing.

**Comment by forman** [comment] 2018-05-22 09:15
> However, there are some operations that don't have a cancel button and that can take some time like "open_dataset"

`open_dataset` now has a progress monitor and is cancelable, however for multiple files only.

>  The last command took a surprising 5 hours to write out a 2.5 GB file...

Holy cow! That's not intended. Note, it may not be the writing itself, but the processing that provides the data to be written (Cate uses "pull processing" through xarray/dask)

**Comment by forman** [comment] 2018-09-27 10:54
@kjpearson can you still reproduce this?

**Comment by kjpearson** [comment] 2018-10-01 11:30
I can now successfully cancel opening datasets. There can be a delay of some minutes before it seems to take effect but it does succesfully cancel.

**Comment by forman** [comment] 2018-10-01 12:36
Ok, closing it, thanks!

**Closed by forman** 2018-10-01 12:36 UTC
Labels: bug, cannot_reproduce, gui
